# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
company: Elix
title: Elix Tech Blog
email: ai.elix.inc[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
 We provide the state-of-the-art AI to other companies. We suggest the best model by reading the latest research papers and implement it.<br><br>
 ディープラーニングを中心とした人工知能・機械学習に特化しています。最新の論文をもとに最適なモデルを提案・実装します。お気軽にご相談ください。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: elix_inc
github_username:  elix-tech

# Build settings
markdown: kramdown
